//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtomicSeller.Models
{
    using System;
    using System.Collections.Generic;

    public partial class ProductDM
    {
        public int ProductID { get; set; }
        public string SKU { get; set; }
        public string MPN { get; set; }
        public string ProductID_Ext { get; set; }
        public string ProductName { get; set; }
        public string StoreKey { get; set; }
        public string MerchantKey { get; set; }
        public Nullable<int> MerchantID { get; set; }
        public string Active { get; set; }
        public string PriceInclTax { get; set; }
        public string Tax { get; set; }
        public string PriceExclTax { get; set; }
        public string TaxRate { get; set; }
        public string Weight { get; set; }
        public Nullable<int> CN23CategoryID { get; set; }
        public string GTIN { get; set; }
        public string ProductWidth { get; set; }
        public string ProductDepth { get; set; }
        public string ProductLength { get; set; }
        public string VariationID { get; set; }
        public string BundleID { get; set; }
        public string FamilyKey { get; set; }
        public string FamilyName { get; set; }
        public string IndustrialID { get; set; }
        public string Industrial { get; set; }
        public string IndustrialRestocking { get; set; }
        public Nullable<System.DateTime> PutSaleDate { get; set; }
        public Nullable<System.DateTime> EndSaleDate { get; set; }
        public string CartonDimension { get; set; }
        public string CartonGTIN { get; set; }
        public string CartonRef { get; set; }
        public Nullable<int> CartonWeight { get; set; }
        public Nullable<int> CartonFloor { get; set; }
        public string CartonBunchingProtocol { get; set; }
        public Nullable<int> PalletWeight { get; set; }
        public Nullable<int> TotalProductsStock { get; set; }
        public Nullable<int> OutOfStockQty { get; set; }
        public Nullable<int> StockMini { get; set; }
        public Nullable<int> StockMaxi { get; set; }
        public Nullable<int> StockAlert { get; set; }
        public Nullable<int> StockMax { get; set; }
        public Nullable<int> StockBuffer { get; set; }
        public Nullable<int> CartonsPerPaletNb { get; set; }
        public Nullable<int> PalletFloor { get; set; }
        public string Fragility { get; set; }
        public string BuyingUnitCode { get; set; }
        public string BuyingUnitName { get; set; }
        public string SalesUnitCode { get; set; }
        public string SalesUnitName { get; set; }
        public Nullable<int> NbProductsPerBuyingUnit { get; set; }
        public Nullable<int> NbProductsPerSalesUnit { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string HSCode { get; set; }
        public Nullable<System.DateTime> ProductToWMSTimeStamp { get; set; }
        public Nullable<System.DateTime> StockUpdateFromWMSTimeStamp { get; set; }
        public string WMSKey { get; set; }
        public string Brand { get; set; }
    }
}
